name: macOS x86_64

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '*.md'
      - 'Documents/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'Documents/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'Documents/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Build XM8 macOS app
        run: |
          cd Builder/macOS
          ./dist_app.sh x86_64
          mv ../../build/xm8.dmg ../../build/XM8_macOS_x86_64.dmg

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: XM8_macOS_x86_64.dmg
          path: build/*.dmg

      - name: Update Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/*.dmg
          overwrite: true